<a href="https://colab.research.google.com/github/neuralstack-hub/DAV-LAB/blob/main/Program1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print("\n1. Numpy Array")
print("Array:",arr)


1. Numpy Array
Array: [10 20 30 40 50]


In [ ]:
print("First element:",arr[0])
print("Third element:",arr[2])
print("Last element:",arr[-1])

First element: 10
Third element: 30
Last element: 50


In [ ]:
print("\n--- Array Slicing ---")
print("First three element:", arr[0:3])
print("Elements from index 2:", arr[2:])
print("last three element:", arr[-3:])


--- Array Slicing ---
First three element: [10 20 30]
Elements from index 2: [30 40 50]
last three element: [30 40 50]


In [ ]:
print("\n--- Basic Array Operations ---")
print("Add 5:", arr + 5)
print("Subtract 5:", arr - 5)
print("Multiply by 2:", arr * 2)
print("Divide by 10:", arr / 10)


--- Basic Array Operations ---
Add 5: [15 25 35 45 55]
Subtract 5: [ 5 15 25 35 45]
Multiply by 2: [ 20  40  60  80 100]
Divide by 10: [1. 2. 3. 4. 5.]


In [ ]:
print("\n --- Mathematical Operations ---")
print("Sum:",np.sum(arr))
print("Mean:",np.mean(arr))
print("Maximum:",np.max(arr))
print("Minimum:",np.min(arr))


 --- Mathematical Operations ---
Sum: 150
Mean: 30.0
Maximum: 50
Minimum: 10


In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60])
new_arr = arr.reshape(2, 3)
print("Original Array:")
print(arr)

print("\nReshaped Array:")
print(new_arr)


Original Array:
[10 20 30 40 50 60]

Reshaped Array:
[[10 20 30]
 [40 50 60]]


In [ ]:
data = {
    "Name": ["Asha", "Ravi", "Meera", "Karan"],
    "Marks": [88,72,91,65],
    "Branch": ["CSE", "ECE", "CSE", "ISE"]
}

df = pd.DataFrame(data)
print("\n---Pandas DataFrame---")
print(df)


---Pandas DataFrame---
    Name  Marks Branch
0   Asha     88    CSE
1   Ravi     72    ECE
2  Meera     91    CSE
3  Karan     65    ISE


In [ ]:
print("Name Column:")
print(df["Name"])

Name Column:
0     Asha
1     Ravi
2    Meera
3    Karan
Name: Name, dtype: object


In [ ]:
print("Name and Marks Column:")
print(df[["Name","Marks"]])

Name and Marks Column:
    Name  Marks
0   Asha     88
1   Ravi     72
2  Meera     91
3  Karan     65


In [ ]:
print("Average Marks:",df["Marks"].mean())
print("Highest Marks:",df["Marks"].max())
print("Lowest Marks:",df["Marks"].min())

Average Marks: 79.0
Highest Marks: 91
Lowest Marks: 65


In [ ]:
print("---Original DataFrame ---")
print(df)
print("---Row Indexing ---")
print("First Row:")
print(df.iloc[0])

print("\nSecond Row:")
print(df.iloc[1])

print("\nThird Row:")
print(df.iloc[2])

print("\nFourth Row:")
print(df.iloc[3])

---Original DataFrame ---
    Name  Marks Branch
0   Asha     88    CSE
1   Ravi     72    ECE
2  Meera     91    CSE
3  Karan     65    ISE
---Row Indexing ---
First Row:
Name      Asha
Marks       88
Branch     CSE
Name: 0, dtype: object

Second Row:
Name      Ravi
Marks       72
Branch     ECE
Name: 1, dtype: object

Third Row:
Name      Meera
Marks        91
Branch      CSE
Name: 2, dtype: object

Fourth Row:
Name      Karan
Marks        65
Branch      ISE
Name: 3, dtype: object


In [ ]:
print("--- Specific values ---")
print("Marks of first student:",df.iloc[0, 1])
print("Marks of Ravi:",df.iloc[1, 1])
print("Branch of meera:",df.iloc[2, 2])
print("Name of Karan:",df.iloc[3, 0])

--- Specific values ---
Marks of first student: 88
Marks of Ravi: 72
Branch of meera: CSE
Name of Karan: Karan


In [ ]:
print("\n--- Data Filtering ---")
result = df[df["Marks"]>85]
print("Students with Marks greater then 85:")
print(result)


--- Data Filtering ---
Students with Marks greater then 85:
    Name  Marks Branch
0   Asha     88    CSE
2  Meera     91    CSE
